<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" href="randcss15.css">
<?php require 'randfunc15.php'; ?>
<title>Random Day</title>
</head>
<body>

<hr>
<p>TROUBLESHOOTING:<br>
Above, (echo statement) confirms the php file is included.<br><br>
What is happening here?<br>
Is it syntax or is there a PEMDAS thing going on?</p>
<hr>
<h1>Hey Hey it's RANDOM Day!</h1>
<div id="genran"><?php genrand(); ?></div>
<div id="showcoded">Return random number ( five ) HARD-CODED in the included php file: <?php echo $t; ?></div><br><br>
<div id="showrand">Return random number (function) GENERATED by the included php file: <?php echo $r; ?></div><br><br>

</body>
</html>